/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_api_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Operation */
        post: operations["resume_operation_api_operations__operation_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness_api_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/evidence-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Links */
        get: operations["get_evidence_links_api_sessions__session_id__evidence_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/evidence/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_sessions__session_id__evidence__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_sessions__session_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Command */
        post: operations["command_api_sessions__session_id___operation__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Health check endpoint returning system status and project identifier.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CandidateAction
         * @description Specific corrective intervention applied to microphone configuration.
         */
        CandidateAction: {
            /**
             * Action Type
             * @enum {string}
             */
            action_type: "CHANNEL_SWITCH" | "ANTENNA_SWITCH" | "BOOM_COVERAGE" | "NO_ACTION";
            /** Mic Id */
            mic_id: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
        };
        /**
         * CandidatePlan
         * @description Proposed corrective plan with explicit hash binding.
         */
        CandidatePlan: {
            /** Action Hash */
            action_hash: string;
            /** Actions */
            actions: components["schemas"]["CandidateAction"][];
            /** Base Config Hash */
            base_config_hash: string;
            /** Constraints Hash */
            constraints_hash: string;
            /** Plan Id */
            plan_id: string;
            /**
             * Plan Version
             * @default 1
             */
            plan_version: number;
            /** Rationale */
            rationale: string;
            /** Tradeoffs */
            tradeoffs?: string[];
        };
        /** Command */
        Command: {
            approval?: components["schemas"]["PlanApproval"] | null;
            /** Constraints */
            constraints?: components["schemas"]["Constraint"][] | null;
            /** Revision */
            revision: number;
            /** Text */
            text?: string | null;
        };
        /**
         * Constraint
         * @description Creative constraint discovered or confirmed by human operator.
         */
        Constraint: {
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /** Constraint Id */
            constraint_id: string;
            /** Exact Source Span */
            exact_source_span: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "CHANNEL_EXCLUSION" | "RIG_LOCK" | "ANTENNA_LOCK" | "BOOM_EXCLUSION" | "CUSTOM";
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /** Source Text */
            source_text: string;
            /**
             * Target Mic
             * @default null
             */
            target_mic: string | null;
        };
        /**
         * ConstraintInterpretation
         * @description Output of Gemini constraint parsing from human natural text.
         */
        ConstraintInterpretation: {
            /** Constraints */
            constraints: components["schemas"]["Constraint"][];
            /** Rationale */
            rationale: string;
            /**
             * Status
             * @enum {string}
             */
            status: "SUPPORTED" | "AMBIGUOUS" | "CONTRADICTORY" | "UNSUPPORTED";
        };
        /** CreateSession */
        CreateSession: {
            /**
             * Mode
             * @default preview
             * @enum {string}
             */
            mode: "preview" | "live";
            /**
             * Preset
             * @default a
             * @enum {string}
             */
            preset: "a" | "b" | "c" | "control";
        };
        /**
         * EvidenceEnvelope
         * @description Normalized evidence record retrieved from Grafana Cloud via MCP.
         */
        EvidenceEnvelope: {
            /** Config Hash */
            config_hash: string;
            /** Evidence Id */
            evidence_id: string;
            /** Mic Id */
            mic_id: string;
            /** Observation Type */
            observation_type: string;
            /**
             * Offset Ms
             * @default null
             */
            offset_ms: number | null;
            /** Query Hash */
            query_hash: string;
            /** Retrieval Time */
            retrieval_time: string;
            /** Run Id */
            run_id: string;
            /** Source Tool */
            source_tool: string;
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Value */
            value: unknown;
        };
        /**
         * EvidenceManifest
         * @description Cryptographic manifest binding cloud evidence, commitments, and run metadata.
         */
        EvidenceManifest: {
            /** Config Hash */
            config_hash: string;
            /** Created At Rfc3339 */
            created_at_rfc3339: string;
            /** Fault Commitment Hash */
            fault_commitment_hash: string;
            /** Manifest Id */
            manifest_id: string;
            /**
             * Metric Count
             * @default 48
             */
            metric_count: number;
            /** Run Id */
            run_id: string;
            /**
             * Sample Count
             * @default 484
             */
            sample_count: number;
            /**
             * Scenario Id
             * @default scene_12_rehearsal
             */
            scenario_id: string;
            /** Scenario Path Hash */
            scenario_path_hash: string;
            /**
             * Scenario Version
             * @default 1.0
             */
            scenario_version: string;
            /** Session Id */
            session_id: string;
            /** Source Audio Hash */
            source_audio_hash: string;
        };
        /**
         * Finding
         * @description Investigation finding produced by Google ADK reasoning agent.
         */
        Finding: {
            /** Affected Mic */
            affected_mic: string;
            /** Competing Explanations */
            competing_explanations?: string[];
            /**
             * Evidence Ids
             * @description Must cite actual EvidenceEnvelope IDs returned by wrapper tools
             */
            evidence_ids: string[];
            /** Interval Ms */
            interval_ms: [
                number,
                number
            ];
            /** Observations */
            observations: string[];
            recommended_action: components["schemas"]["CandidateAction"];
            /**
             * Status
             * @enum {string}
             */
            status: "RISK_IDENTIFIED" | "HEALTHY" | "INCONCLUSIVE";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MicSample
         * @description 100ms raw observation sample for a specific microphone.
         */
        MicSample: {
            /** Battery Pct */
            battery_pct: number;
            /**
             * Config Hash
             * @default
             */
            config_hash: string;
            /**
             * Is Clipped
             * @default false
             */
            is_clipped: boolean;
            /**
             * Is Dropout
             * @default false
             */
            is_dropout: boolean;
            /** Link Margin Db */
            link_margin_db: number;
            /** Mic Id */
            mic_id: string;
            /** Offset Ms */
            offset_ms: number;
            /** Quality */
            quality: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Timestamp Rfc3339
             * @default
             */
            timestamp_rfc3339: string;
        };
        /**
         * ObservedRun
         * @description Fresh run evidence assembled strictly from Grafana Cloud MCP queries.
         */
        ObservedRun: {
            /** Completion Marker Present */
            completion_marker_present: boolean;
            /** Config Hash */
            config_hash: string;
            /** End Time Rfc3339 */
            end_time_rfc3339: string;
            /**
             * Fault Commitment Hash
             * @default
             */
            fault_commitment_hash: string;
            /**
             * Has Conflicting Duplicates
             * @default false
             */
            has_conflicting_duplicates: boolean;
            /**
             * Identical Duplicate Count
             * @default 0
             */
            identical_duplicate_count: number;
            /**
             * Is Truncated
             * @default false
             */
            is_truncated: boolean;
            /** @default null */
            manifest: components["schemas"]["EvidenceManifest"] | null;
            /** Metrics */
            metrics: components["schemas"]["PerSecondMetric"][];
            /** Retrieved Sample Count */
            retrieved_sample_count: number;
            /** Run Id */
            run_id: string;
            /** Samples */
            samples: components["schemas"]["MicSample"][];
            /**
             * Scenario Path Hash
             * @default
             */
            scenario_path_hash: string;
            /** Session Id */
            session_id: string;
            /**
             * Source Audio Hash
             * @default
             */
            source_audio_hash: string;
            /** Start Time Rfc3339 */
            start_time_rfc3339: string;
        };
        /**
         * PerSecondMetric
         * @description Per-second aggregated telemetry metric summary for a microphone.
         */
        PerSecondMetric: {
            /** Clipping Duration Ms */
            clipping_duration_ms: number;
            /**
             * Config Hash
             * @default
             */
            config_hash: string;
            /** Dropout Duration Ms */
            dropout_duration_ms: number;
            /** Mic Id */
            mic_id: string;
            /** Min Battery Pct */
            min_battery_pct: number;
            /** Min Link Margin Db */
            min_link_margin_db: number;
            /** Min Quality */
            min_quality: number;
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Second */
            second: number;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Timestamp Rfc3339
             * @default
             */
            timestamp_rfc3339: string;
        };
        /**
         * PlanApproval
         * @description Human decision record binding exact plan version and hashes.
         */
        PlanApproval: {
            /** Action Hash */
            action_hash: string;
            /** Approved */
            approved: boolean;
            /** Approved At */
            approved_at?: string;
            /**
             * Approved By
             * @default sound_mixer
             */
            approved_by: string;
            /** Base Config Hash */
            base_config_hash: string;
            /** Constraints Hash */
            constraints_hash: string;
            /** Plan Id */
            plan_id: string;
            /** Plan Version */
            plan_version: number;
        };
        /**
         * RunConfig
         * @description Configuration applied to the simulator for a rehearsal run.
         */
        RunConfig: {
            /**
             * Antenna Selection
             * @default A
             */
            antenna_selection: string;
            /** Backup Sources */
            backup_sources?: {
                [key: string]: string;
            };
            /** Channel Assignments */
            channel_assignments?: {
                [key: string]: number;
            };
            /**
             * Scenario Id
             * @default scene_12_rehearsal
             */
            scenario_id: string;
        };
        /**
         * ShotContext
         * @description Context for the 12-second rehearsed cinema scene.
         */
        ShotContext: {
            /** Available Antennas */
            available_antennas?: string[];
            /** Available Backup Sources */
            available_backup_sources?: {
                [key: string]: string[];
            };
            /** Available Channels */
            available_channels?: {
                [key: string]: number[];
            };
            /**
             * Critical Dialogue Text
             * @default do not cut the feed
             */
            critical_dialogue_text: string;
            /**
             * Critical Line End Ms
             * @default 6800
             */
            critical_line_end_ms: number;
            /**
             * Critical Line Start Ms
             * @default 4900
             */
            critical_line_start_ms: number;
            /**
             * Duration Ms
             * @default 12000
             */
            duration_ms: number;
            /** Mic Ids */
            mic_ids?: string[];
            /**
             * Notes
             * @default Exterior alleyway scene. Metal fire escape causes RF reflection.
             */
            notes: string;
            /** Performer Names */
            performer_names?: {
                [key: string]: string;
            };
            /**
             * Sample Period Ms
             * @default 100
             */
            sample_period_ms: number;
            /**
             * Scenario Path Hash
             * @default 4f738b55be5534c0fa6b986e66164f9bf3cf8813a408719bc45d6148386b0336
             */
            scenario_path_hash: string;
            /**
             * Shot Id
             * @default shot_012_alleyway
             */
            shot_id: string;
            /**
             * Source Audio Hash
             * @default d7afbe4395aad34313673f18fae92c90be7fd34e33d072fe882cf3ed24c50c03
             */
            source_audio_hash: string;
            /**
             * Synthetic Disclosure
             * @default Explicitly synthetic speech generated via Google Cloud Vertex AI Text-to-Speech API. Phrase timings are approximate intervals based on audio energy profile for rehearsal alignment, not forced word-level alignments.
             */
            synthetic_disclosure: string;
            /**
             * Timing Precision
             * @default approximate
             */
            timing_precision: string;
            /**
             * Transcript
             * @default Perimeter sensors detected breached access at section nine; whatever happens, do not cut the feed until our squad secures point alpha.
             */
            transcript: string;
            /**
             * Vulnerable Word
             * @default cut
             */
            vulnerable_word: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationResult
         * @description Deterministic verifier evaluation result computed from fresh cloud evidence.
         */
        VerificationResult: {
            /** Baseline Run Id */
            baseline_run_id: string;
            /** Comparison Run Id */
            comparison_run_id: string;
            /** Completeness Passed */
            completeness_passed: boolean;
            /** Constraints Passed */
            constraints_passed: boolean;
            /** Crosscheck Passed */
            crosscheck_passed: boolean;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Dialogue Coverage Passed */
            dialogue_coverage_passed: boolean;
            /** Evidence Hashes */
            evidence_hashes: {
                [key: string]: string;
            };
            /** Failure Reasons */
            failure_reasons?: string[];
            /**
             * Terminal Status
             * @enum {string}
             */
            terminal_status: "VERIFIED" | "NOT_VERIFIED" | "INCONCLUSIVE";
            /** Thresholds Passed */
            thresholds_passed: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_operation_api_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_operation_api_operations__operation_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_readiness_api_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_links_api_sessions__session_id__evidence_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_sessions__session_id__evidence__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_sessions__session_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    command_api_sessions__session_id___operation__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                operation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
