"""create_turn_reservations_and_sessions

Revision ID: b7fabd84d9b9
Revises:
Create Date: 2026-09-08 22:12:15.380989

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7fabd84d9b9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "turn_reservations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workflow_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("operation_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(
        op.f("ix_turn_reservations_workflow_id"), "turn_reservations", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_sessions",
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("workflow_id", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("baseline_run_id", sa.String(length=128), nullable=True),
        sa.Column("comparison_run_id", sa.String(length=128), nullable=True),
        sa.Column("config_hash", sa.String(length=128), nullable=True),
        sa.Column("plan_binding_hash", sa.String(length=128), nullable=True),
        sa.Column("plan_version", sa.Integer(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_workflow_sessions_workflow_id"), "workflow_sessions", ["workflow_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_sessions_workflow_id"), table_name="workflow_sessions")
    op.drop_table("workflow_sessions")
    op.drop_index(op.f("ix_turn_reservations_workflow_id"), table_name="turn_reservations")
    op.drop_table("turn_reservations")
    # ### end Alembic commands ###
